//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LooneyBankModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankBranchAddress
    {
        public int BankBranchAddressID { get; set; }
        public int BankBranchID { get; set; }
        public int BankAddressTypeID { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual BankAddressType BankAddressType { get; set; }
        public virtual BankBranch BankBranch { get; set; }
    }
}
