//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LooneyBankModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LooneyBankEntities : DbContext
    {
        public LooneyBankEntities()
            : base("name=LooneyBankEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Bank> Banks { get; set; }
        public DbSet<BankAddressType> BankAddressTypes { get; set; }
        public DbSet<BankBranch> BankBranches { get; set; }
        public DbSet<BankBranchAddress> BankBranchAddresses { get; set; }
        public DbSet<BankBranchPhone> BankBranchPhones { get; set; }
        public DbSet<PhoneType> PhoneTypes { get; set; }
    }
}
