//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankBranch
    {
        public BankBranch()
        {
            this.BankBranchAddresses = new HashSet<BankBranchAddress>();
            this.BankBranchPhones = new HashSet<BankBranchPhone>();
        }
    
        public int BankBranchID { get; set; }
        public int BankID { get; set; }
        public bool IsOpen { get; set; }
        public bool IsMainBankBranch { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual ICollection<BankBranchAddress> BankBranchAddresses { get; set; }
        public virtual ICollection<BankBranchPhone> BankBranchPhones { get; set; }
    }
}
